### PR TITLE
Make sure run lint don't fix only show the error

### PR DESCRIPTION
**Pull request by alicoding**

### CODE REVIEW

**Comment by alicoding** [comment]
@alanmoo

**Comment by alanmoo** [comment]
Uh, sure? Is this behavior from mofo-style though?

**Comment by alicoding** [comment]
Recommended by @gvn

**Comment by alanmoo** [comment]
Ok, R+

**Comment by gvn** [comment]
Yep, that LGTM. :+1:

**Comment by gvn** [comment]
It's pretty much to avoid Travis modifying your code (if you're using it...).

**Comment by alanmoo** [comment]
Ah cool

**Pull request merged**
