### PR TITLE
CSP

### PR DESCRIPTION
**Pull request by alanmoo**
I think this addresses https://github.com/MozillaFoundation/encryption_campaign/issues/202, but when it comes to back end stuff I'm like ¯\\\_(ツ)_/¯

### CODE REVIEW

**Comment by alicoding** [comment]
this LGTM, but maybe you can get @cadecairos to look over this for you as well if you like.

**Comment by alanmoo** [comment]
@cadecairos is that reaction an R+?

**Comment by alanmoo** [comment]
I added a few more items to the whitelist and deployed to https://lit-mountain-52009.herokuapp.com/encrypt/social/3. Everything seems to work, though I get a warning when clicking the Facebook share button. @adamlofting can you check if this does what you need for optimizely?

@cadecairos maybe you can give some guidance on the Facebook frame issue?

(And if this is all sorted out before I wake up, feel free to merge and deploy so that Adam can move forward with the other ticket.)

**Comment by cadecairos** [comment]
@alanmoo I don't see an error WRT a Facebook iframe, but I do see a few issues:

- The play video icon (an svg as a data URI) isn't loading due to the img-src directive. (Firefox + Chrome)
- A GA scripts isn't executing because it's loading as a data URI (Firefox)
- Another, unamed script isn't loading (Firefox) - I'm trying to pinpoint which, or if it's double reporting the one I mentioned above.

**Comment by alanmoo** [comment]
@cadecairos check it out now. I still see that Facebook issue in Safari, but it also seems to work as expected....

**Comment by adamlofting** [comment]
Close, but we also need: 

```
frameSrc: ['https://app.optimizely.com']
```

I think it will work after that.

**Comment by alanmoo** [comment]
@adamlofting I replaced it with `childSrc` as per http://content-security-policy.com, but I guess that didn't do it? I can throw that in.

**Comment by adamlofting** [comment]
@alanmoo Ah, interesting. Perhaps `frame-ancestors` is the one we need? Is that the sites that are allowed to frame us (rather than site's we're allowed to frame).

**Comment by alanmoo** [comment]
I've made another adjustment now that I know exactly what's not working. Give it a shot, @adamlofting.

**Comment by adamlofting** [comment]
urg! sorry... nearly there...

We need to add `https://app.optimizely.com` to the scriptSrc data array as well.

**Comment by alanmoo** [comment]
Give it another shot

**Comment by adamlofting** [comment]
Success :fireworks: 

screenshot 2016-03-15 17 03 28

**Pull request merged**
