### PR TITLE
2016 content (don't push to prod until Aug 1)

### PR DESCRIPTION
**Pull request by alanmoo**

### CODE REVIEW

**Comment by alanmoo** [comment]
@kristinashu When you get a chance, take a look at [the structural changes](https://peaceful-mount-rainier-35186.herokuapp.com/en-US/open-web-fellows). Content still needs updating, but I believe this meets design requirements (I had to do a some work, particularly with spacing).

**Comment by alanmoo** [comment]
@Melechuga Can you make sure I have access to the content docs? I believe I primarily need fellows summaries and FAQs.

**Comment by vanessarhinesmith** [comment]
@alanmoo All set. I gave you access to both documents.

**Comment by alanmoo** [comment]
Ah, thank you!

**Comment by alanmoo** [comment]
Scratch that, @kristinashu - save for 2 icons, this could use a full design review as all the content is now in place.

**Comment by kristinashu** [comment]
@alanmoo here are a few assets and notes:
- [ ] landing page should be "2016 Fellows" tab instead of "Overview" tab (https://peaceful-mount-rainier-35186.herokuapp.com/en-US/open-web-fellows/)
- [ ] here are the needed icons for Expectations of Fellows:
[icons.zip](https://github.com/mozilla/advocacy.mozilla.org/files/350825/icons.zip)
- [ ] since you've made the list style for Expectations of Fellows can you please do the same for Stipend and Financial Benefits section?
- [ ] hero image for 2016 Fellows (so it's different from 2015): 
[2016-hero@2x.jpg.zip](https://github.com/mozilla/advocacy.mozilla.org/files/350866/2016-hero.2x.jpg.zip)
- [ ] FAQ accordions have an extra lines on the sides and top/bottom when they shouldn't:
Staging screenshot in FF 47 for mac:
screen shot 2016-07-06 at 1 18 07 pm
Comp:
screen shot 2016-07-06 at 1 38 26 pm

**Comment by alanmoo** [comment]
@kristinashu I've made all those changes. In addition, I left-aligned the paragraphs on the overview page as they were inconsistent and look better on mobile when left aligned (though I left the headers of the fellows pages centered.

**Comment by alanmoo** [comment]
@gvn or @ScottDowne can you draw straws and start doing a code review?

**Comment by kristinashu** [comment]
Thanks @alanmoo. Some of the text alignment looks pretty weird on the Overview page (https://peaceful-mount-rainier-35186.herokuapp.com/en-US/open-web-fellows/overview) but it gets the job done and the rest of the changes are good.

**Comment by alanmoo** [comment]
@kristinashu What specifically looks weird? I can change center/left alignment pretty easily.

**Comment by kristinashu** [comment]
@alanmoo the mix of center and left aligned text is what is weird and makes it hard to read but I not sure there's a quick fix (as is, I don't think making it all left aligned will work). Thanks tho!

**Comment by ScottDowne** [comment]
Code wise this is fairly straight forward. I have no issues.

**Comment by alanmoo** [comment]
Great. @gvn any comments?

**Comment by ScottDowne** [comment]
Actually, design wise, looks like on mobile some of the pages have text that go right up to the side. Could use some left and right padding on some blocks.

**Comment by alanmoo** [comment]
I feel like the 25px padding that's on everything else at mobile is too much, especially with the FAQ's and nested bullet points. I put 5px on for now, @kristinashu want to take a look on mobile?

**Comment by kristinashu** [comment]
Thanks for pointing that out @ScottDowne! Could we bump up the padding to 10px? 

When a sentence goes onto two lines on the FAQ page there is too much line height, making it hard to read (screen cap below). Please reduce the height:

screen shot 2016-07-12 at 8 34 15 am

**Comment by alanmoo** [comment]
Take a look now

**Comment by kristinashu** [comment]
Looks good!

**Comment by hannahkane** [comment]
Just a note: @vanessarhinesmith has asked that we don't push this to production until August 1

**Comment by alanmoo** [comment]
@ScottDowne You don't have anything that's going to land before Monday that might break this, right?

**Comment by ScottDowne** [comment]
There is a bug in submissions to basket, forcing us to use legacy code in basket that may be removed. I needed to remove that asap, so probably, yes, I'll be landing something today or tomorrow.

I don't think I'll break anything, but we're also not using gitflow, so anything you land, blocks shipping to prod.

We should land this Monday or Sunday night.

**Comment by alanmoo** [comment]
Let me know when you're working on that so I can compare the branches. My gut is telling me that shouldn't really conflict, but I'll take a look.

**Comment by ScottDowne** [comment]
I should be done everything now, my fix is on prod, and it worked for me, and moco is testing it now.

**Comment by alanmoo** [comment]
Great, no conflicts still so this should go up fine.

**Comment by ScottDowne** [comment]
Do you have creds to get this on prod?

**Comment by alanmoo** [comment]
Yeah. I promoted it, I believe it's being propagated by the CDN right now and that's why it doesn't appear to be live.

-Alan Mooiman,

MoFo Engineering

Eastern Time Zone

On Mon, Aug 01, 2016 at 9:20 AM ScottDowne

<
mailto:ScottDowne <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Do you have creds to get this on prod?

—

You are receiving this because you modified the open/close state.

Reply to this email directly,
https://github.com/mozilla/advocacy.mozilla.org/pull/211#issuecomment-236578275
, or

**Comment by ScottDowne** [comment]
Yeah it'll take a bit. If you need to test that it works you can open the
prod heroku app directly from the heroku dashboard.

**Comment by alanmoo** [comment]
Yeah, it works there- though side note: I just realized it's Safari that's got me directing to the wrong URL- I believe it uses lowercase for the "accept-language" headers, and that's how `en-us` is getting applied as the locale. So that may be a bigger issue than we thought...

**Pull request merged**
