### PR TITLE
Nuked Wordpress - DO NOT MERGE!

### PR DESCRIPTION
**Pull request by alicoding**
DO NOT MERGE!!

This should be a PR against gh-pages branch, but I don't have permission to create a branch for this repo.

@jbuck or @mmmavis can you help me fix this?

----------

@ScottDowne you can probably R? this now :)

-----

### CODE REVIEW

**Comment by alicoding** [comment]
@ScottDowne you can also test it from this link http://alicoding.github.io/advocacy.mozilla.org/

**Comment by alicoding** [comment]
A bit of a context here of what I did since the patch is really big.

1. Optimized all images in `common/assets` directory
2. Removed unused CSS and make each pages to have its own CSS file
3. Removed everything related to WP (as the commit message and branch name stated there ;) )

To run this patch locally simply run:

`npm install`

Then

`npm start`

**Comment by mmmavis** [comment]
@alicoding  done

**Comment by alicoding** [comment]
@mmmavis thanks!

**Comment by alicoding** [comment]
Closing this one since we want to do it against gh-pages branch : https://github.com/mozilla/advocacy.mozilla.org/pull/14

**Pull request closed without merging**
