### PR TITLE
updated text and menus and graphics

### PR DESCRIPTION
**Pull request by brettgaylor**
Added new funder text
added node graphics to call for applications pages
updated menus
commented out mobile versions of sub menus

### CODE REVIEW

**Comment by simonwex** [comment]
R+!

**Comment by brettgaylor** [comment]
whats the pro tip for closing another issue within this issue?

**Comment by simonwex** [comment]
In your pull request, you can write "closes #{number of the issue}"

**Comment by mmmavis** [comment]
@brettgaylor https://help.github.com/articles/closing-issues-via-commit-messages/ :smile_cat:

**Pull request merged**
