### PR TITLE
Playing with npm scripts a bit to reduce complexity without too much …

### PR DESCRIPTION
**Pull request by ScottDowne**
…compromise

### CODE REVIEW

**Comment by ScottDowne** [comment]
@alicoding or @alanmoo thoughts on this? Do you see any issues I may have missed?

My goal is thrice fold.

1. reduce complexity for the scripts.
2. remove double babel run on `npm start`
3. remove watch from `npm install` on dev

There are compromises, but I suspect small, and might actually have fixes if I think about it more?

1. we only have one kind of build, and it's production worthy. watch is not a build, and is only dev
2. start does a watch, and heroku only does `npm start` if there is no procfile, which we have. Not super obvious though.
3. remove watch from `npm install` on dev (adding this again as it might be intended)

Flow looks like this:

dev
`npm install` installs stuff
`postinstall` does a build
`npm start` starts a watch

prod
`npm install` installs stuff
`postinstall` does a build
procfile runs, runs server

**Comment by ScottDowne** [comment]
Also let me know if you have any questions!

**Comment by alanmoo** [comment]
I like the flow better, but a few thoughts:

Localization isn't kicking in for me when I run a fresh `npm i` and `npm start`. I remember having problems before though, not sure if it's related to these changes.

Live reload doesn't seem to happen- I can't recall if that's in the repo before this though.

**Comment by alanmoo** [comment]
Also why are we running babel at all, not just using the webpack loader?

**Comment by ScottDowne** [comment]
@alanmoo cool, good responses.

Yeah, live reload isn't setup here.

I'll test localization, and comment back with what I find.

webpack loader was used at one point. Reasoning is:

Server side had issues resolving imports in memory friendly ways at run time, or had a slow build. Moving to command line babel solved this, and also happened to do what the webpack loader was.

I really like when client side and server side can start sharing solutions.

**Pull request merged**
