### PR TITLE
Open Fellows

### PR DESCRIPTION
**Pull request by alicoding**

### CODE REVIEW

**Comment by alicoding** [comment]
@ScottDowne R?

**Comment by ScottDowne** [comment]
R+ but, can we merge it and build it on some sort of staging, and ping me again for a final look?

If there already is a staging, merge it and ping me the staging link.

**Comment by alicoding** [comment]
@ScottDowne we don't have staging like at this point... gh-pages seems to be our live site right now, so staging is my branch at this time.

I think we should change that to be production = master and gh-pages = staging... what do you think @ScottDowne ?

**Comment by ScottDowne** [comment]
merge this than.

Sounds like you need QA more than a single review.

I did notice the little double >> icon looks like it should be a link to http://alicoding.github.io/advocacy.mozilla.org/open-web-fellows/

**Comment by alicoding** [comment]
I couldn't find that icon you're referring to?

**Comment by ScottDowne** [comment]
This icon http://alicoding.github.io/advocacy.mozilla.org/common/assets/center-button.png

**Pull request merged**
