### PR TITLE
encrypt home banner

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by alicoding** [comment]
r+ from me
@alanmoo wanna take a look at this as well?

**Comment by alanmoo** [comment]
When does this come in to play?

**Comment by alicoding** [comment]
CC @valianttry

**Comment by HPaulJohnson** [comment]
@alanmoo this is ready to go live when you have time.

**Comment by alicoding** [comment]
@HPaulJohnson done it should be on production soon.

**Pull request closed without merging**
