### PR TITLE
Avoiding horizontal scroll

### PR DESCRIPTION
**Pull request by jessuircleydson**
**BEFORE**
captura de tela 2017-12-04 as 12 05 07

**AFTER**
captura de tela 2017-12-04 as 12 07 46

### CODE REVIEW

**Comment by alanmoo** [comment]
Hi, thanks for the contribution! Which url is that screenshot from?

**Comment by jessuircleydson** [comment]
Where did i see that?
Apparently that error occur anywhere the footer was applied, so maybe every page haha.
I saw here https://advocacy.mozilla.org/, so i reproduced the same in my local machine.
The reason is here `` /net-neutrality/footer.less ``

**Comment by ScottDowne** [comment]
Thanks for finding and fixing this @jessuircleydson !

What happened is recently we added a new page advocacy.mozilla.org/net-neutrality with a slightly modified footer. It's leaking CSS into the rest of the page it seems.

It would be great too if we can fix the new footer so it doesn't leak again in the future. I've filed https://github.com/mozilla/advocacy.mozilla.org/issues/478 to future proof this, if you're interested @jessuircleydson you're welcome to take a look.

**Comment by jessuircleydson** [comment]
@ScottDowne yeah i can take a look

**Pull request merged**
