### PR TITLE
fixed some broken URLs for fellows 2017 personal websites

### PR DESCRIPTION
**Pull request by drewrwilson**
looks like the http was missing in some of the links, resulting in broken links on the webpage. I updated those links

BIG CONGRATS TO THE NEW FELLOWS!

### CODE REVIEW

**Comment by ScottDowne** [comment]
Hey @drewrwilson sorry I missed this earlier.

It looks like the links were already updated in this patch: https://github.com/mozilla/advocacy.mozilla.org/commit/9a873e4423b030e18ac21e8155f4de58e5289a04

After doing a rebase on your patch, we still have this: https://github.com/mozilla/advocacy.mozilla.org/pull/393

I'm happy to merge it if it still looks good to you :)

**Comment by ScottDowne** [comment]
Oh wait, looks like `linkName` isn't a property in the 2015 page.

**Comment by ScottDowne** [comment]
Updated it to support the added link, let me know what you think :)

**Comment by drewrwilson** [comment]
Hey @ScottDowne, I just looked at this webpage today to send to someone. It looks like the link for my website is still incorrect :/ My website links to https://www.rishabn.com/ but it should be htts://drewrwilson.com

**Comment by drewrwilson** [comment]
actually, I re-forked the repo and tried to make the change again. I'm closing this pull request because I opened another one with the correct fix: https://github.com/mozilla/advocacy.mozilla.org/pull/539

**Pull request closed without merging**
